tap "cmacrae/formulae"
tap "hashicorp/tap"
tap "nikitabobko/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "oven-sh/bun"
tap "wez/wezterm"

# Using aerospace for now
# instance_eval(File.read("./yabai.Brewfile"))

# loading another Brewfile: https://github.com/Homebrew/homebrew-bundle/issues/521
instance_eval(File.read("./fonts.Brewfile"))

brew "actionlint"
brew "bat"
brew "coreutils"
brew "curl"
brew "difftastic"
brew "eza"
brew "elvish"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "freetype"
brew "fzf"
brew "gawk"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "git"
brew "glab"
brew "go-jsonnet"
brew "graphviz"
brew "harfbuzz"
brew "hashicorp/tap/terraform"
brew "helix"
brew "htop"
brew "imagemagick"
brew "inxi"
brew "jq"
brew "ldns"
brew "libqalculate"
brew "librsvg"
brew "marksman"
brew "mtr"

# use proto instead
# brew "n"

brew "ncdu"
brew "neofetch"
brew "nushell"
brew "oven-sh/bun/bun"
brew "pueue"
brew "ripgrep"
brew "sapling"
brew "starship"
brew "stow"
brew "svgo"
brew "tailscale"
brew "tesseract"
brew "tealdeer"
brew "tree"
brew "watchman"
brew "webp"
brew "youtube-dl"
cask "alacritty"
cask "android-platform-tools"
cask "git-credential-manager"
cask "google-chrome"
cask "karabiner-elements"
cask "keepassxc"
cask "keycastr"
cask "keymapp"
cask "kitty"
cask "linearmouse"
cask "nikitabobko/tap/aerospace"
cask "rancher"
cask "raycast"
cask "sublime-merge"
cask "visual-studio-code"
cask "wezterm"
cask "zed"