//! Canonical content + lifecycle for the user-facing Nickel files that blend owns.
//!
//! `orders/order.contract.ncl` and `orders/metadata.ncl` mirror the Rust
//! definitions in `crate::nickel::schema` and `crate::metadata`. They are
//! generated and committed to the repo so that LSPs and other tooling can
//! resolve them without running blend.
//!
//! This module owns:
//! - The canonical `&'static str` content (`contract_ncl`, `metadata_ncl`).
//! - Writer entrypoint for `init` / `sync`: `ensure_orders_ready`
//!   (creates the orders dir if missing, then writes/refreshes both files).
//! - Reader entrypoint for `view` / `status` / `table`: `assert_orders_ready`
//!   (errors with a `blend init` hint if the dir or files are missing/stale).

/// Full content of `orders/order.contract.ncl`.
pub fn contract_ncl() -> &'static str {
    CONTRACT_NCL
}

/// Full content of `orders/metadata.ncl`.
pub fn metadata_ncl() -> &'static str {
    METADATA_NCL
}

const CONTRACT_NCL: &str = r#"# DO NOT EDIT — generated by `blend init` / `blend sync`.
# Source of truth: blend/src/nickel/schema.rs and blend/src/metadata.rs.
# Regenerate with: blend init  (or any sync run).

{
  contract_version = 2,

  Format = std.contract.from_predicate (fun x =>
    std.is_string x &&
    std.array.elem x ["toml", "json", "jsonc", "yaml", "space_pair_lines", "space_record_lines", "equals_record_lines", "plaintext"]
  ),

  SandboxMode = std.contract.from_predicate (fun x =>
    std.is_string x &&
    std.array.elem x ["prefer", "force", "never"]
  ),

  WhenCondition = {
    os | Array String | optional,
    arch | Array String | optional,
    hostname | Array String | optional,
  },

  # Individual file/folder entry
  FileEntry = {
    name | String | optional,           # Destination filename (defaults to from_file)
    from_file | String | optional,      # External file/folder to copy (plaintext mode)
    from_config | Dyn | optional,       # Inline structured config data
    prefix | Array String | optional,   # Destination prefixes (overrides global)
    format | Format | optional,         # Override format (inferred from name if omitted)
    ignore | Array String | optional,   # Keys to exclude from diff
    when | WhenCondition | optional,    # Per-file condition
    symlink | Bool | optional,          # Create symlink instead of copying (from_file only)
    exclude | Array String | optional,  # Glob patterns to skip in from_file directories
    local | String | optional,          # Local overlay directory (from_file directories only)
    immutable | Bool | optional,        # Set OS immutable flag after deploying
  },

  OrderMeta = {
    files | Array FileEntry | optional,
    prefix | Array String | optional,   # Default prefix for all files
    when | WhenCondition | optional,    # Global condition
    ignore | Array String | optional,   # Global ignore keys
  },

  Order = {
    blend | OrderMeta,
  },

  # Additional contract for the generated `orders/blend/order.ncl`.
  # Keeps blend's own config from accepting stale or unknown config keys.
  BlendConfig = {
    sandbox | SandboxMode | optional,
  },

  BlendFileEntry = {
    from_config | BlendConfig | optional,
    ..
  },

  BlendOrder = {
    blend | {
      files | Array BlendFileEntry | optional,
      ..
    },
  },

  Metadata = {
    os | String,
    arch | String,
    hostname | String,
    user | String,
    home | String,
    desktop | String | optional,
  },
}
"#;

const METADATA_NCL: &str = r#"# DO NOT EDIT — generated by `blend init` / `blend sync`.
# Per-machine values are injected at runtime via Nickel `&` merge.
# These defaults exist only so LSP/editors can resolve `metadata.<field>`
# and so the file satisfies the Metadata contract on its own.

let { Metadata, .. } = import "./order.contract.ncl" in
({
  os | default = "linux",
  arch | default = "x86_64",
  hostname | default = "host",
  user | default = "user",
  home | default = "/home/user",
} | Metadata)
"#;

use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::migration::{self, MigrationCheck};
use crate::output::log;

/// Writer-mode entrypoint for `init` / `sync`: create the orders
/// directory if missing, then write or refresh the contract + metadata files.
/// Idempotent. Mirrors `assert_orders_ready` (the reader-mode counterpart).
///
/// When `upgrade` is true, a breaking contract migration is allowed and the
/// user's contract file is overwritten with the current version. When false,
/// breaking migrations cause an error directing the user to `blend init --upgrade`.
pub fn ensure_orders_ready(orders_dir: &Path, upgrade: bool) -> Result<()> {
    ensure_fresh(orders_dir, upgrade)
}

/// Internal helper: write the contract + metadata files if they are missing
/// or out of date. Creates `orders_dir` if it doesn't exist (so `blend init`
/// works on a fresh checkout). Idempotent. Logs `regenerated <path>` only
/// when an actual write happens. The public entrypoint is
/// [`ensure_orders_ready`].
fn ensure_fresh(orders_dir: &Path, upgrade: bool) -> Result<()> {
    std::fs::create_dir_all(orders_dir)
        .with_context(|| format!("Failed to create {}", orders_dir.display()))?;

    let contract_path = orders_dir.join("order.contract.ncl");

    // Check existing contract version before overwriting.
    if let Ok(existing) = std::fs::read_to_string(&contract_path) {
        let user_version = migration::read_contract_version(&existing);
        match migration::check(user_version) {
            MigrationCheck::UpToDate => {}
            MigrationCheck::NonBreaking { .. } => {
                migration::print_migration_hints(user_version);
                log::info("Non-breaking contract update — applying automatically.");
            }
            MigrationCheck::Breaking { .. } => {
                if !upgrade {
                    migration::print_migration_hints(user_version);
                    bail!(
                        "Contract requires a breaking upgrade (v{} → v{}). \
                         Run `blend init --upgrade` to apply.",
                        user_version,
                        migration::CURRENT_CONTRACT_VERSION
                    );
                }
                migration::print_migration_hints(user_version);
                log::info("Applying breaking contract upgrade.");
            }
        }
    }

    write_if_changed(&contract_path, contract_ncl())?;
    write_if_changed(&orders_dir.join("metadata.ncl"), metadata_ncl())?;
    Ok(())
}

/// Internal helper: verify both files exist and match the expected content.
/// Returns an error pointing the user at `blend init` if not. The public
/// entrypoint is [`assert_orders_ready`].
fn assert_fresh(orders_dir: &Path) -> Result<()> {
    check_fresh(&orders_dir.join("order.contract.ncl"), contract_ncl())?;
    check_fresh(&orders_dir.join("metadata.ncl"), metadata_ncl())?;
    Ok(())
}

/// Reader-mode precondition: verify the orders directory exists AND that the
/// blend-owned schema files are present and fresh. Used by `view`, `status`,
/// `table` so all three readers surface the same diagnostics.
pub fn assert_orders_ready(orders_dir: &Path) -> Result<()> {
    if !orders_dir.is_dir() {
        bail!("Orders directory not found: {}", orders_dir.display());
    }
    assert_fresh(orders_dir)
}

fn write_if_changed(path: &Path, expected: &str) -> Result<()> {
    let actual = match std::fs::read_to_string(path) {
        Ok(s) => Some(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            return Err(e).with_context(|| format!("Failed to read {}", path.display()));
        }
    };
    if actual.as_deref() == Some(expected) {
        return Ok(());
    }
    std::fs::write(path, expected)
        .with_context(|| format!("Failed to write {}", path.display()))?;
    log::info(&format!("regenerated {}", path.display()));
    Ok(())
}

fn check_fresh(path: &Path, expected: &str) -> Result<()> {
    let actual = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => bail!(
            "{} is missing. Run `blend init` (or `blend sync`) to refresh.",
            path.display()
        ),
        Err(e) => {
            return Err(e).with_context(|| format!("Failed to read {}", path.display()));
        }
    };
    if actual != expected {
        bail!(
            "{} is out of date. Run `blend init` (or `blend sync`) to refresh.",
            path.display()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn contract_ncl_contains_expected_definitions() {
        let s = contract_ncl();
        for needle in [
            "contract_version = 2,",
            "Format =",
            "SandboxMode =",
            "WhenCondition =",
            "FileEntry =",
            "OrderMeta =",
            "Order =",
            "BlendConfig =",
            "BlendOrder =",
            "Metadata =",
        ] {
            assert!(s.contains(needle), "contract_ncl missing `{needle}`");
        }
    }

    #[test]
    fn metadata_ncl_contains_defaults_and_contract() {
        let s = metadata_ncl();
        assert!(s.contains(r#"import "./order.contract.ncl""#));
        assert!(s.contains("| Metadata)"));
        for field in ["os", "arch", "hostname", "user", "home"] {
            assert!(
                s.contains(&format!("{field} | default")),
                "missing default for `{field}`"
            );
        }
    }

    fn read(path: &Path) -> String {
        std::fs::read_to_string(path).unwrap()
    }

    #[test]
    fn ensure_fresh_creates_missing_files() {
        let tmp = TempDir::new().unwrap();
        ensure_fresh(tmp.path(), true).unwrap();
        assert_eq!(read(&tmp.path().join("order.contract.ncl")), contract_ncl());
        assert_eq!(read(&tmp.path().join("metadata.ncl")), metadata_ncl());
    }

    #[test]
    fn ensure_fresh_is_idempotent() {
        let tmp = TempDir::new().unwrap();
        ensure_fresh(tmp.path(), true).unwrap();
        let mtime1 = std::fs::metadata(tmp.path().join("metadata.ncl"))
            .unwrap()
            .modified()
            .unwrap();
        // Sleep briefly so a second write would have a different mtime.
        std::thread::sleep(std::time::Duration::from_millis(20));
        ensure_fresh(tmp.path(), true).unwrap();
        let mtime2 = std::fs::metadata(tmp.path().join("metadata.ncl"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(mtime1, mtime2, "second ensure_fresh should not rewrite");
    }

    #[test]
    fn ensure_fresh_overwrites_stale_content() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("metadata.ncl"), "stale junk\n").unwrap();
        ensure_fresh(tmp.path(), true).unwrap();
        assert_eq!(read(&tmp.path().join("metadata.ncl")), metadata_ncl());
    }

    #[test]
    fn assert_fresh_passes_when_files_match() {
        let tmp = TempDir::new().unwrap();
        ensure_fresh(tmp.path(), true).unwrap();
        assert_fresh(tmp.path()).unwrap();
    }

    #[test]
    fn assert_fresh_errors_when_missing() {
        let tmp = TempDir::new().unwrap();
        let err = assert_fresh(tmp.path()).unwrap_err();
        let msg = format!("{err}");
        assert!(
            msg.contains("missing"),
            "expected `missing` in error, got: {msg}"
        );
        assert!(
            msg.contains("blend init"),
            "expected `blend init` hint, got: {msg}"
        );
    }

    #[test]
    fn assert_fresh_errors_when_stale() {
        let tmp = TempDir::new().unwrap();
        ensure_fresh(tmp.path(), true).unwrap();
        std::fs::write(tmp.path().join("metadata.ncl"), "tampered\n").unwrap();
        let err = assert_fresh(tmp.path()).unwrap_err();
        let msg = format!("{err}");
        assert!(
            msg.contains("out of date"),
            "expected `out of date`, got: {msg}"
        );
        assert!(msg.contains("blend init"));
    }

    #[test]
    fn ensure_fresh_creates_missing_directory() {
        let tmp = TempDir::new().unwrap();
        let nested = tmp.path().join("a/b/c");
        // nested does NOT exist yet
        ensure_fresh(&nested, true).unwrap();
        assert!(nested.join("order.contract.ncl").exists());
        assert!(nested.join("metadata.ncl").exists());
    }

    #[test]
    fn assert_orders_ready_errors_when_dir_missing() {
        let tmp = TempDir::new().unwrap();
        let nonexistent = tmp.path().join("does-not-exist");
        let err = assert_orders_ready(&nonexistent).unwrap_err();
        let msg = format!("{err}");
        assert!(
            msg.contains("Orders directory not found"),
            "expected `Orders directory not found`, got: {msg}"
        );
    }

    #[test]
    fn assert_orders_ready_passes_when_files_fresh() {
        let tmp = TempDir::new().unwrap();
        ensure_fresh(tmp.path(), true).unwrap();
        assert_orders_ready(tmp.path()).unwrap();
    }

    #[test]
    fn ensure_orders_ready_creates_files_in_missing_directory() {
        let tmp = TempDir::new().unwrap();
        let nested = tmp.path().join("a/b");
        ensure_orders_ready(&nested, true).unwrap();
        assert!(nested.join("order.contract.ncl").exists());
        assert!(nested.join("metadata.ncl").exists());
    }

    /// Catches the most likely future regression: adding a field to
    /// `crate::metadata::Metadata` without also updating `CONTRACT_NCL`
    /// (the `Metadata` contract row) and/or `METADATA_NCL` (the default).
    /// Without this test, the failure mode would be a contract violation
    /// raised by Nickel at every `blend evaluate`, several layers removed
    /// from the cause.
    #[test]
    fn metadata_struct_agrees_with_generated_contract() {
        use crate::metadata::Metadata;
        use crate::nickel::NickelEvaluator;
        use std::path::PathBuf;

        let tmp = TempDir::new().unwrap();
        ensure_orders_ready(tmp.path(), true).unwrap();

        // Stub order that touches every Metadata field through the contract.
        // If the contract is missing a field that Metadata has, Nickel will
        // error with a contract violation when evaluating this. If the
        // contract has a field that Metadata doesn't, the merge will produce
        // an extra field that fails the closed-record contract.
        let order_name = tmp.path().join("schema_agreement_order");
        std::fs::create_dir_all(&order_name).unwrap();
        std::fs::write(
            order_name.join("order.ncl"),
            r#"let metadata = import "../metadata.ncl" in
let { Order, .. } = import "../order.contract.ncl" in
{
  blend = {
    files = [
      {
        name = "agreement.toml",
        from_config = {
          os = metadata.os,
          arch = metadata.arch,
          hostname = metadata.hostname,
          user = metadata.user,
          home = metadata.home,
        },
      },
    ],
  },
} | Order
"#,
        )
        .unwrap();

        let metadata = Metadata {
            os: "linux".to_string(),
            arch: "x86_64".to_string(),
            hostname: "host".to_string(),
            desktop: None,
            home: PathBuf::from("/home/user"),
            user: "user".to_string(),
        };
        let evaluator = NickelEvaluator::new(&metadata);
        let result = evaluator.evaluate(&order_name.join("order.ncl"));
        assert!(
            result.is_ok(),
            "Metadata struct + generated contract drifted apart. \
             Update CONTRACT_NCL and METADATA_NCL in nickel::generated to \
             match the current Metadata fields. Error: {:?}",
            result.err()
        );
    }

    #[test]
    fn fixtures_match_generated() {
        let fixture_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests")
            .join("fixtures")
            .join("orders");
        let contract = std::fs::read_to_string(fixture_dir.join("order.contract.ncl")).unwrap();
        let metadata = std::fs::read_to_string(fixture_dir.join("metadata.ncl")).unwrap();
        assert_eq!(
            contract,
            contract_ncl(),
            "tests/fixtures/orders/order.contract.ncl is out of date with generated::contract_ncl(); regenerate it"
        );
        assert_eq!(
            metadata,
            metadata_ncl(),
            "tests/fixtures/orders/metadata.ncl is out of date with generated::metadata_ncl(); regenerate it"
        );
    }
}
